version: '3.8'

services:
  # שירות בסיס הנתונים
  db:
    image: postgres:18
    container_name: event_scale_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mollokapi1+
      POSTGRES_DB: event_scale_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ממשק גרפי לניהול בסיס הנתונים
  pgadmin:
    image: dpage/pgadmin4
    container_name: event_scale_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data: